### ISSUE TITLE
NAPS2 7.5.1.0 - MacOs 15 Sequoia - Not connecting to printer anymore

### ISSUE THREAD

**Issue by pbm94** [cyanfish/naps2#458] opened 2024-09-24 15:11 UTC
**Describe the bug**
Here in the office we have, a few MacMini's. After the update to Sequoia, the app dont comunicate correctly to the scanner.

**To Reproduce**
1. Update to MacOs 15 Sequoia
2. Try to scan
3. After some time, it show Failed to Open a connection to the device
4. ![Captura de Tela 2024-09-24 às 12 08 47](https://github.com/user-attachments/assets/3d3dcc9c-c501-4645-8073-452cc06747bd)

**Expected behavior**
Should simply scan.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs
 - Version 15

**Comment by cyanfish** [comment] 2024-09-24 22:20
Does it work if you use [builtin](https://support.apple.com/en-ca/guide/mac-help/mh28032/mac) Apple scanning?

If it's a network scanner you can also try selecting "ESCL Driver" when you choose a device.

**Comment by tobiashinz** [comment] 2024-10-11 06:11
For me it is also not working anymore since uograding to Sequoia. Does it have to do with the new local network access control mechanism?

**Comment by barryh2024** [comment] 2024-10-21 16:52
I have Sequoia 15.0.1 and NAPP2 7.5.2.0 and Brother MFC-J480DW printer/scanner.  I had problems with Sequoia and  my scanner but those seem to have worked themselves out.  I got the same message as above (I think) before trying again today.    Now I am getting connected, can set up my 2 profiles (glass/feeder), and it will go through the scanning process.  However, no scans show up in NAPS2, just blank.  I can create a new issue or just wait.  Scanning in MAC isn't terrible without NAPS2 unlike Windows where NAPS2 is essential.

**Comment by cyanfish** [comment] 2024-10-21 19:40
@barryh2024 Can you try with 7.5.1? Someone else was reporting that problem with 7.5.2.

**Comment by nonubot123** [comment] 2024-10-24 20:08
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by barryh2024** [comment] 2024-10-24 20:18
> to fix your trouble check this solution...

Spam.

**Comment by pbm94** [comment] 2024-10-24 20:46
> @cyanfish I installed 7.5.1 and it works as expected, so I'll stick with that for now. It is not working in 7.5.2 nor in 8.0b1. Thanks for all of your hard work.

I cant make i work in either 7.5.1 or 7.5.2. Haven't tried the 8.0b1.

**Comment by tobiashinz** [comment] 2024-10-25 06:06
Switching in printer selection view from "Apple Driver" to "ESCL Driver" triggered the Sequoia prompt if NAPS2 may connect to devices on the local network. Then it started working again.

**Comment by cyanfish** [comment] 2024-10-25 15:58
@pbm94 Did you try switching to ESCL Driver and back as suggested by Tobias?

**Comment by pbm94** [comment] 2024-10-25 16:42
Yes, I Have!

With the ESCL driver the print didn’t connect via IP address or the host name


Atenciosamente,



Paulo Meier

Departamento de Desenvolvimento

[signatureImage]
________________________________

**Comment by Hwiet** [comment] 2024-12-18 01:52
> I have Sequoia 15.0.1 and NAPP2 7.5.2.0 and Brother MFC-J480DW printer/scanner. I had problems with Sequoia and my scanner but those seem to have worked themselves out. I got the same message as above (I think) before trying again today. Now I am getting connected, can set up my 2 profiles (glass/feeder), and it will go through the scanning process. However, no scans show up in NAPS2, just blank. I can create a new issue or just wait. Scanning in MAC isn't terrible without NAPS2 unlike Windows where NAPS2 is essential.

I'm also having this issue (MacBook Air M1 2020, Sequoia 15.1.1 and NAPP2 7.5.2.0) where no scans show up after a seemingly successful scan. Nothing in the debug log suggests an issue either.

<details>
<summary>debuglog.txt</summary>
2024-12-17 20:43:07.9707 2535 Scanning with ScanDevice { Driver = Apple, ID = 00553635-3734-374A-3358-313138383233, Name = Brother DS-640, IconUri =  } 
2024-12-17 20:43:08.0257 2535 Scan source: Feeder; bit depth: Grayscale; dpi: 300; page size: 8.5x11 in 
2024-12-17 20:43:08.1581 2537 ICC: Opening session 
2024-12-17 20:43:09.0030 2537 DidOpenSession (null) 
2024-12-17 20:43:09.0056 2537 ICC: Waiting for ready 
2024-12-17 20:43:09.0097 2537 DidBecomeReady 
2024-12-17 20:43:09.0097 2537 ICC: Selecting unit 
2024-12-17 20:43:09.0277 2537 DidSelectFunctionalUnit ICScannerFunctionalUnitDocumentFeeder (null) 
2024-12-17 20:43:09.0307 2537 DidSelectFunctionalUnit ICScannerFunctionalUnitDocumentFeeder (null) 
2024-12-17 20:43:09.0307 2537 ICC: Setting scan parameters 
2024-12-17 20:43:09.0369 2537 ICC: Requesting scan 
2024-12-17 20:43:09.0806 2537 DidReceiveStatusInformation ICScannerStatusWarmingUp 
2024-12-17 20:43:13.4480 2537 DidReceiveStatusInformation ICScannerStatusWarmUpDone 
2024-12-17 20:43:14.1524 2537 DidScanToBandData buffer complete 
2024-12-17 20:43:14.1580 2537 DidScanToBandData buffer complete 
2024-12-17 20:43:14.1587 2537 DidCompleteScan (null) 
2024-12-17 20:43:14.1587 2537 ICC: Waiting for scan results 
2024-12-17 20:43:14.1587 2537 ICC: Closing session 
2024-12-17 20:43:14.1609 2537 DidCloseSession (null) 
2024-12-17 20:43:14.1609 2537 ICC: Scan success 
2024-12-17 20:43:14.1641 2537 Image data: width 2550, height 3300, type Gray, comp 1, bits/comp 8, bits/pixel 8, bytes/row 2552, data len 8485400 
2024-12-17 20:43:14.1641 2537 Image data: width 2550, height 3300, type Gray, comp 1, bits/comp 8, bits/pixel 8, bytes/row 2552, data len 8421600 
2024-12-17 20:43:14.1641 2537 Flushing image with color sync profile /System/Library/Frameworks/ICADevices.framework/Versions/A/Resources/Scanner Gray Profile.icc 
2024-12-17 20:43:14.1641 2537 Flushing image with color sync profile /System/Library/Frameworks/ICADevices.framework/Versions/A/Resources/Scanner Gray Profile.icc 
</details>

**Comment by fberlakovich** [comment] 2024-12-19 07:58
> @cyanfish I installed 7.5.1 and it works as expected, so I'll stick with that for now. It is not working in 7.5.2 nor in 8.0b1. Thanks for all of your hard work.

Same experience (MacOS 15.1.1 (24B91)), 7.5.1 works, newer versions do not show the scanned image. No errors in error log, no suspicious output in debug log. 
I managed to build NAPS2 from source to investigate, but then ran out of time. If you can give me pointers of where to look or things to try, I am happy to help. 
Thanks for your amazing work!

**Comment by barryh2024** [comment] 2024-12-21 23:19
> @cyanfish I installed 7.5.1 and it works as expected, so I'll stick with that for now. It is not working in 7.5.2 nor in 8.0b1. Thanks for all of your hard work.

Adding some more data...  

My issue with no scans showing up is on a 2018 i5 Mac mini.  I upgraded to Sequoia 15.2 with no change.  7.5.1 working, 7.5.2 does not.  

However, I just got a new 2024 M4 Mac mini running Sequoia 15.2 and 7.5.2 up and running successfully.  

Thanks again for your work.

**Comment by cyanfish** [comment] 2024-12-30 22:54
The regressions from 7.5.1->7.5.2 should be fixed in [7.5.3](https://www.naps2.com/download). If you're still having issues with Sequoia try Settings>Privacy & Security>Local Network and allow NAPS2.

**Closed by cyanfish** 2024-12-30 22:54 UTC
